<?php
/**
 * BankTransactionRulesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BankTransactionRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BankTransactionRulesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkBankTransactionRules
     *
     * Performs bulk actions on an array of bank_transation rules.
     *
     */
    public function testBulkBankTransactionRules()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteBankTransactionRule
     *
     * Deletes a bank_transaction rule.
     *
     */
    public function testDeleteBankTransactionRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editBankTransactionRule
     *
     * Shows a bank_transaction for editing.
     *
     */
    public function testEditBankTransactionRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankTransactionRules
     *
     * Gets a list of bank_transaction_rules.
     *
     */
    public function testGetBankTransactionRules()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankTransactionRulesCreate
     *
     * Gets a new blank bank_transaction rule object.
     *
     */
    public function testGetBankTransactionRulesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showBankTransactionRule
     *
     * Shows a bank_transaction.
     *
     */
    public function testShowBankTransactionRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeBankTransactionRule
     *
     * Adds a bank_transaction rule.
     *
     */
    public function testStoreBankTransactionRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateBankTransactionRule
     *
     * Updates a bank_transaction Rule.
     *
     */
    public function testUpdateBankTransactionRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
