<?php
/**
 * CompaniesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompaniesApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompaniesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteCompany
     *
     * Deletes a company.
     *
     */
    public function testDeleteCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editCompany
     *
     * Shows an company for editting.
     *
     */
    public function testEditCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompanies
     *
     * Gets a list of companies.
     *
     */
    public function testGetCompanies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompaniesCreate
     *
     * Gets a new blank company object.
     *
     */
    public function testGetCompaniesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setDefaultCompany
     *
     * Sets the company as the default company..
     *
     */
    public function testSetDefaultCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showCompany
     *
     * Shows an company.
     *
     */
    public function testShowCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeCompany
     *
     * Adds a company.
     *
     */
    public function testStoreCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCompany
     *
     * Updates an company.
     *
     */
    public function testUpdateCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadCompanies
     *
     * Uploads a document to a company.
     *
     */
    public function testUploadCompanies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
