<?php
/**
 * ExpensesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExpensesApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpensesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkExpenses
     *
     * Performs bulk actions on an array of expenses.
     *
     */
    public function testBulkExpenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteExpense
     *
     * Deletes a client.
     *
     */
    public function testDeleteExpense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editExpense
     *
     * Shows a client for editting.
     *
     */
    public function testEditExpense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpenses
     *
     * Gets a list of expenses.
     *
     */
    public function testGetExpenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExpensesCreate
     *
     * Gets a new blank client object.
     *
     */
    public function testGetExpensesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showExpense
     *
     * Shows a client.
     *
     */
    public function testShowExpense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeExpense
     *
     * Adds a client.
     *
     */
    public function testStoreExpense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateExpense
     *
     * Updates a client.
     *
     */
    public function testUpdateExpense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
