<?php
/**
 * RecurringQuotesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecurringQuotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecurringQuotesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for actionRecurringQuote
     *
     * Performs a custom action on an RecurringQuote.
     *
     */
    public function testActionRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bulkRecurringQuotes
     *
     * Performs bulk actions on an array of recurring_quotes.
     *
     */
    public function testBulkRecurringQuotes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRecurringQuote
     *
     * Deletes a RecurringQuote.
     *
     */
    public function testDeleteRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editRecurringQuote
     *
     * Shows an RecurringQuote for editting.
     *
     */
    public function testEditRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRecurringQuotes
     *
     * Gets a list of recurring_quotes.
     *
     */
    public function testGetRecurringQuotes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRecurringQuotesCreate
     *
     * Gets a new blank RecurringQuote object.
     *
     */
    public function testGetRecurringQuotesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showRecurringQuote
     *
     * Shows an RecurringQuote.
     *
     */
    public function testShowRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeRecurringQuote
     *
     * Adds a RecurringQuote.
     *
     */
    public function testStoreRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRecurringQuote
     *
     * Updates an RecurringQuote.
     *
     */
    public function testUpdateRecurringQuote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
