<?php
/**
 * RecurringInvoicesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecurringInvoicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecurringInvoicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for actionRecurringInvoice
     *
     * Performs a custom action on an RecurringInvoice.
     *
     */
    public function testActionRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bulkRecurringInvoices
     *
     * Performs bulk actions on an array of recurring_invoices.
     *
     */
    public function testBulkRecurringInvoices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRecurringInvoice
     *
     * Deletes a RecurringInvoice.
     *
     */
    public function testDeleteRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editRecurringInvoice
     *
     * Shows an RecurringInvoice for editting.
     *
     */
    public function testEditRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRecurringInvoices
     *
     * Gets a list of recurring_invoices.
     *
     */
    public function testGetRecurringInvoices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRecurringInvoicesCreate
     *
     * Gets a new blank RecurringInvoice object.
     *
     */
    public function testGetRecurringInvoicesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showRecurringInvoice
     *
     * Shows an RecurringInvoice.
     *
     */
    public function testShowRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeRecurringInvoice
     *
     * Adds a RecurringInvoice.
     *
     */
    public function testStoreRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRecurringInvoice
     *
     * Updates an RecurringInvoice.
     *
     */
    public function testUpdateRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadRecurringInvoice
     *
     * Uploads a document to a recurring_invoice.
     *
     */
    public function testUploadRecurringInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
