<?php
/**
 * VendorsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Invoice Ninja
 *
 * Invoice Ninja. Open Source Invoicing lives here.
 *
 * The version of the OpenAPI document: 5.5.58
 * Contact: contact@invoiceninja.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IvkeyMinds\InvoiceNinjaClient\Test\Api;

use \IvkeyMinds\InvoiceNinjaClient\Configuration;
use \IvkeyMinds\InvoiceNinjaClient\ApiException;
use \IvkeyMinds\InvoiceNinjaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VendorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  IvkeyMinds\InvoiceNinjaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VendorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkVendors
     *
     * Performs bulk actions on an array of vendors.
     *
     */
    public function testBulkVendors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteVendor
     *
     * Deletes a client.
     *
     */
    public function testDeleteVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editVendor
     *
     * Shows a client for editting.
     *
     */
    public function testEditVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVendors
     *
     * Gets a list of vendors.
     *
     */
    public function testGetVendors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVendorsCreate
     *
     * Gets a new blank client object.
     *
     */
    public function testGetVendorsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showVendor
     *
     * Shows a client.
     *
     */
    public function testShowVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for storeVendor
     *
     * Adds a client.
     *
     */
    public function testStoreVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateVendor
     *
     * Updates a client.
     *
     */
    public function testUpdateVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadVendor
     *
     * Uploads a document to a vendor.
     *
     */
    public function testUploadVendor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
